on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5
      with:
        submodules: recursive

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@c7450ba673e133f5ee30098b3b54f444d3a2ca2d
      with:
        version: nightly

    - name: Run tests
      run: forge test --use 0.5.10
